class Emojis {
    constructor(simbolo) {
        this.simbolo = simbolo;
    }
}

const listaEmojis = [
    new Emojis("☠️"),
    new Emojis("😡"),
    new Emojis("😀"),
    new Emojis("🤖"),
    new Emojis("😎"),
    new Emojis("🤩"),
    new Emojis("👻"),
    new Emojis("😈"),
    new Emojis("😺"),
    new Emojis("🥶"),
    new Emojis("😋"),
    new Emojis("👁️"),
    new Emojis("💀"),
    new Emojis("🧠"),
    new Emojis("🦁"),
    new Emojis("🦂"),
    new Emojis("🦍"),
    new Emojis("⚡"),
    new Emojis("☣️"),
    new Emojis("🔱"),
    new Emojis("💲"),
    new Emojis("🎌"),
    new Emojis("🖐️"),
    new Emojis("🤑"),
    new Emojis("🎁"),
    new Emojis("🏆"),
    new Emojis("⚽"),
    new Emojis("🍔"),
    new Emojis("🙂"),
    new Emojis("⚔️"),
    new Emojis("🏴‍☠️"),
    new Emojis("🚀"),
    new Emojis("🎮"),
    new Emojis("📱"),
    new Emojis("❤️"),
    new Emojis("🔥"),
    new Emojis("🇦🇷"),
    new Emojis("🤠"),
    new Emojis("🦸‍♂️"),
    new Emojis("🦇"),
    new Emojis("🧟‍♀️"),
    new Emojis("🐺"),
    new Emojis("🦬"),
    new Emojis("🦖"),
    new Emojis("🦣"),
    new Emojis("🗼"),
    new Emojis("🏎️"),
    new Emojis("🏍️"),
    new Emojis("🚁"),
    new Emojis("🌑"),
    new Emojis("✈️"),
    new Emojis("♣️"),
    new Emojis("♦️"),
    new Emojis("♟️"),
    new Emojis("🏀"),
    new Emojis("🔔"),
    new Emojis("💣"),
    new Emojis("🪓"),
    new Emojis("💊"),
    new Emojis("🪬")
];